server:
  port: 8081

spring:
  profiles.active: dev
  application:
    name: api-server
  messages:
    basename: i18n.messages
    encoding: UTF-8
  # json返回时对null不进行序列化
  jackson:
    #date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:com/zhuzhu/project/api/mapper/*.xml
  typeAliasesPackage: com.zhuzhu.project.api.model

thymeleaf:
  prefix: classpath:/templates/  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5